name: compilation
on: 
    push:
        branches:
            - main

# Ma définition de job qui va s'exécuter sur la machine virtuelle
jobs:
    compilation: #nom donnée
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up JDK 21
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'
            
            - name: Fournir accès au runner
              run: chmod +x mvnw

            - name: Compilation du projet Maven
              run: ./mvnw compile
              
            - name: Compilation test
              run: ./mvnw test
