name: compilation
on: 
    push:
        branches:
            - main

# Ma définitio de job qui va s'exécuter sur la machine virtuelle
jobs:
    compilation: #nom donnée
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
            - uses: actions/checkout@v5

            - name: Set up JDK 21
            uses: actions/setup-java@21
            with:
                distribution: 'temurin'
                java-version: '25'
            
            - name: Fournir accès au runner
            run: chmod +x

            - name: Compilation du projet Maven
            run: ./mvw compile
